version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/hospital-service.war
  discarded-paths: yes